version: "3"

services:
  test_db:
    image: postgres
#    expose:
#      - "5433"
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=luboy
      - POSTGRES_USER=luboy
      - POSTGRES_PASSWORD=luboy
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
#    expose:
#      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      - test_db